### ISSUE TITLE
ISIC Challenges (tag metadata)

### ISSUE THREAD

**Issue by PascalSchimmler** [ImageMarkup/isic-cli#10]
In other downloaders, the images are tagged with the ISIC challenges, in which they are used, which is super useful if you want to compare your results/ your model to others.
Could we add this information to the metadata?

**Comment by danlamanna** [comment]
Hi Pascal,

There are no plans at this time to expose the challenge information directly in the metadata file. For now, your goal can be accomplished with a couple of small steps.

1. Run `isic collection list` to determine which collections are for challenges
   For instance, the identifiers for the 2016 challenge collections are `61` and `74`.
2. Run `isic metadata download --limit 0 --collections 61,74`

At this point, your CSV should contain only the metadata for the 2016 challenge. This step can be repeated for any of the challenges (or any other collection for that matter).
