### ISSUE TITLE
Only 1000 images downloaded out of 57000-ish

### ISSUE THREAD

**Issue by IfuChan** [ImageMarkup/isic-cli#16]
Hey, I wrote the command `isic image download --search 'benign_malignant:"benign"' images/` to download all the benign images, which in the isic-archive shows 57319 images. But, after running the command, it only downloaded 1000 images. Could you help me in getting all the images. Thank you.
![Screenshot 2022-07-16 222239](https://user-images.githubusercontent.com/74062350/179363489-d0726525-971d-42e0-a486-3b306a9b326c.jpg)

**Comment by danlamanna** [comment]
By default the CLI only downloads 1,000 images. You can add `--limit 0` to disable the limit and download everything.
