### ISSUE TITLE
Throws error while using a search string to filter images

### ISSUE THREAD

**Issue by raghukamma** [ImageMarkup/isic-cli#17]
I am trying to filter and download images using below command:

**isic image download --search 'diagnosis:"melanoma"' images/**

I am getting below error:

**Usage: isic image download [OPTIONS] OUTDIR**
**Try 'isic image download -h' for help.**

**Error: Invalid value for '-s' / '--search': Invalid search query string "'diagnosis:melanoma'"**

Could you please let me know what am I doing wrong here?
I am doing an assignment and I wanted to use your dataset for that project.

**Comment by danlamanna** [comment]
It looks like you're quoting the entire thing, try running:
```
isic image download --search 'diagnosis:"melanoma"' images/ 
```
or just
```
isic image download --search diagnosis:melanoma images/
```
