### ISSUE TITLE
Can't install isic-cli with pip (and request for better documentation)

### ISSUE THREAD

**Issue by ignaciohrdz** [ImageMarkup/isic-cli#3]
I just tried to install `isic-cli` as the guide said:

`pip install isic-cli`

But I am getting an error message.

`ERROR: Could not find a version that satisfies the requirement isic-cli (from versions: none)`
`ERROR: No matching distribution found for isic-cli`

I tried looking for some explanations of how to do this properly but I couldn't find anything (not even in the [forum](https://forum.isic-archive.com/)). Would it be possible to expand this part of the documentation? I may not be the only one who does not understand how exactly one should install `isic-cli`.

Thanks!

**Comment by danlamanna** [comment]
I suspect you're running an older version of Python (less than 3.9), this could be confirmed by running `python -V`. Upgrading to python 3.9 or later should let you install the CLI.

**Comment by danlamanna** [comment]
FYI, it appears the latest versions of pip produce a slightly more helpful error message in this scenario:
```
(tmp-3f0f89fe4b78e37) ➜  tmp-3f0f89fe4b78e37 pip install isic-cli
ERROR: Ignored the following versions that require a different python version: 0.0.2 Requires-Python >=3.9; 0.0.3 Requires-Python >=3.9; 0.0.4 Requires-Python >=3.9; 0.0.5 Requires-Python >=3.9; 0.0.6 Requires-Python >=3.9; 0.0.7 Requires-Python >=3.9; 0.0.8 Requires-Python >=3.9; 0.1.1 Requires-Python >=3.9; 0.1.2 Requires-Python >=3.9; 0.2.0 Requires-Python >=3.9; 0.2.1 Requires-Python >=3.9; 0.2.2 Requires-Python >=3.9; 0.2.3 Requires-Python >=3.9; 0.3.0 Requires-Python >=3.9; 0.4.0 Requires-Python >=3.9; 0.5.0 Requires-Python >=3.9; 0.6.0 Requires-Python >=3.9; 1.0.0 Requires-Python >=3.9; 1.1.0 Requires-Python >=3.9; 1.2.0 Requires-Python >=3.9; 2.0.0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement isic-cli (from versions: none)
ERROR: No matching distribution found for isic-cli                        
```

**Comment by ignaciohrdz** [comment]
Thanks for the quick response!

I was able to install it after switching to `3.9.0`, but `isic user login` doesn't seem to work. 

The error occurs in:

```
 File "[...]/envs/isic-download-3.9.0/lib/python3.9/site-packages/isic_cli/cli/__init__.py", line 86, in cli
    check_for_newer_version()
 File "[...]/envs/isic-download-3.9.0/lib/python3.9/site-packages/isic_cli/utils/version.py", line 56, in check_for_newer_version
    upgrade_type_available = upgrade_type(this_version, newest_version)
File "[...]/envs/isic-download-3.9.0/lib/python3.9/site-packages/isic_cli/utils/version.py", line 24, in upgrade_type
    if to_version.major > from_version.major:
AttributeError: 'Version' object has no attribute 'major'
```

The error has also thrown this message, which may be useful for finding the problem:

```
isic-cli: v2.0.0
python:   v3.9.0
time:     2022-05-12T17:20:48.667725
os:       Linux-5.4.0-1065-aws-x86_64-with-glibc2.27
env:      -
user:     -
command:  isic user login
```

Is this a bug or is there something that I'm still missing?

**Comment by danlamanna** [comment]
Hmm, looks like a bug. Can you paste the output of `pip freeze`?

**Comment by ignaciohrdz** [comment]
After switching again to `3.10.0` I've been able to log in 🙌

The previous environment was a clean one, with nothing else than isic-cli. I deleted the environment before reading your answer, but this is what I had done before, so you should probably get the same `pip freeze`:

pyenv install 3.9.0
pyenv local 3.9.0
python3 -m venv isic-download-3.9.0
source isic-download-3.9.0/bin/activate
pip install isic-cli

**Comment by danlamanna** [comment]
Glad it's working, thanks for the bug report.
