### ISSUE TITLE
Invalid search query string error

### ISSUE THREAD

**Issue by ifk99** [ImageMarkup/isic-cli#39]
I am trying to dowload images using the filters diagnosis:basal cell carcinoma AND benign_malignant:malignant, but I always get error "Invalid search query string". I have tried in differents ways, and even filtering only by diagnosis:basal cell carcinoma I get the same error. I have been able to download images using other filters, but not this one.
Here are some of the options I tried:
isic image download --search "diagnosis:basal cell carcinoma"
isic image download --search diagnosis:"basal cell carcinoma"
isic image download --search "diagnosis:basal cell carcinoma AND benign_malignant:malignant"
isic image download --search "benign_malignant:malignant AND diagnosis:basal cell carcinoma"
isic image download --search "benign_malignant:malignant AND diagnosis:"basal cell carcinoma""
isic image download --search benign_malignant:malignant AND diagnosis:"basal cell carcinoma"
isic image download --search 'benign_malignant:malignant AND diagnosis:"basal cell carcinoma"'

**Comment by danlamanna** [comment]
Sorry, the quoting needed for spaces is quite finicky at the moment. Take a look at my comment here - https://github.com/ImageMarkup/isic-cli/issues/14#issuecomment-1180671418 and let me know if that helps.

**Comment by ifk99** [comment]
Thanks for the reply. I tried: 
isic image download --search 'diagnosis:"basal cell carcinoma"' testtt/
and it still gives me the invalid search query string error, I also tested the same one that you mentioned in the comment, but gives me the same error:
isic image download --search 'diagnosis:"solar lentigo"' images_test/

**Comment by danlamanna** [comment]
Hmm. Are you on Windows by chance? And if so, are you using powershell or cmd? I recall running into weird quoting issues there e.g. https://forum.isic-archive.com/t/downloading-images-using-isic-cli/1505/5.

**Comment by ifk99** [comment]
Yes I am using Windows cmd. After looking in this forum I was able able to make it work by using:
isic image download --search "diagnosis:""squamous cell carcinoma"" AND benign_malignant:malignant"
Thank you so much for the help!
