### ISSUE TITLE
how i can download part of the dataset?

### ISSUE THREAD

**Issue by andrushoksoftteco** [ImageMarkup/isic-cli#42]

**Comment by andrushoksoftteco** [comment]
> Without more detail I'm not sure I can help, make sure you read the instructions for downloading data: https://github.com/ImageMarkup/isic-cli#downloading-images.

the whole set of images takes tens of gigabytes. Can I upload part of the full data (meta data, mask, etc.)?

**Comment by danlamanna** [comment]
That's described in the readme I linked above.
