### ISSUE TITLE
which version of dataset can I access with this steps?

### ISSUE THREAD

**Issue by taghilooniya** [ImageMarkup/isic-cli#46]
hi. as I read, there are several version of ISIC dataset(ISIC 2016, ISISC 2018 and etc). which version of dataset can I access with this steps(with .json)?

**Comment by danlamanna** [comment]
I'm not sure what you mean. Running `isic collection list` will show the available collections for download with the CLI. Downloading collections with the CLI will provide the images and metadata (in CSV format).

**Comment by danlamanna** [comment]
Closing, feel free to reopen if there's anything else.
